In [1]:
#importing required libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
#link to the site I wish to scrape
url = "https://www.basketball-reference.com/playoffs/"

In [3]:
#creating a response object
response = requests.get(url)

In [4]:
response

In [5]:
data = response.text

In [6]:
#parsing the data
soup = BeautifulSoup(data,"html.parser")

In [7]:
#extract column headers into a list
headers = [th.getText() for th in soup.find_all("tr", limit=2)[1].find_all('th')]

In [8]:
headers

['Year',
 'Lg',
 'Champion',
 'Runner-Up',
 'Finals MVP',
 '\xa0',
 'Points',
 'Rebounds',
 'Assists',
 'Win Shares']

In [9]:
#get rows from table
rows = soup.find_all("tr")[2:]
rows_data = [[td.getText() for td in rows[i].find_all("td")] for i in range(len(rows))]

In [10]:
#slicing the first 41 rows from the table
rows_data = rows_data[:41]

In [11]:
rows_data

[['NBA',
  'Golden State Warriors',
  'Boston Celtics',
  'S. Curry',
  '',
  'J. Tatum (615)',
  'A. Horford (214)',
  'J. Tatum (148)',
  'J. Butler (3.8)'],
 ['NBA',
  'Milwaukee Bucks',
  'Phoenix Suns',
  'G. Antetokounmpo',
  '',
  'G. Antetokounmpo (634)',
  'G. Antetokounmpo (269)',
  'J. Holiday (199)',
  'G. Antetokounmpo (3.7)'],
 ['NBA',
  'Los Angeles Lakers',
  'Miami Heat',
  'L. James',
  '',
  'A. Davis (582)',
  'L. James (226)',
  'L. James (184)',
  'A. Davis (4.5)'],
 ['NBA',
  'Toronto Raptors',
  'Golden State Warriors',
  'K. Leonard',
  '',
  'K. Leonard (732)',
  'D. Green (223)',
  'D. Green (187)',
  'K. Leonard (4.9)'],
 ['NBA',
  'Golden State Warriors',
  'Cleveland Cavaliers',
  'K. Durant',
  '',
  'L. James (748)',
  'D. Green (222)',
  'L. James (198)',
  'L. James (5.2)'],
 ['NBA',
  'Golden State Warriors',
  'Cleveland Cavaliers',
  'K. Durant',
  '',
  'L. James (591)',
  'K. Love (191)',
  'L. James (141)',
  'L. James (4.3)'],
 ['NBA',
  'Cleveland Cavaliers',
  'Golden State Warriors',
  'L. James',
  '',
  'K. Thompson (582)',
  'D. Green (228)',
  'R. Westbrook (198)',
  'L. James (4.7)'],
 ['NBA',
  'Golden State Warriors',
  'Cleveland Cavaliers',
  'A. Iguodala',
  '',
  'L. James (601)',
  'D. Howard (238)',
  'L. James (169)',
  'S. Curry (3.9)'],
 ['NBA',
  'San Antonio Spurs',
  'Miami Heat',
  'K. Leonard',
  '',
  'K. Durant (563)',
  'T. Duncan (211)',
  'R. Westbrook (153)',
  'L. James (4.3)'],
 ['NBA',
  'Miami Heat',
  'San Antonio Spurs',
  'L. James',
  '',
  'L. James (596)',
  'T. Duncan (214)',
  'L. James (152)',
  'L. James (5.2)'],
 ['NBA',
  'Miami Heat',
  'Oklahoma City Thunder',
  'L. James',
  '',
  'L. James (697)',
  'L. James (224)',
  'R. Rondo (227)',
  'L. James (5.8)'],
 ['NBA',
  'Dallas Mavericks',
  'Miami Heat',
  'D. Nowitzki',
  '',
  'D. Nowitzki (582)',
  'T. Chandler (193)',
  'J. Kidd (153)',
  'L. James (3.8)'],
 ['NBA',
  'Los Angeles Lakers',
  'Boston Celtics',
  'K. Bryant',
  '',
  'K. Bryant (671)',
  'P. Gasol (255)',
  'R. Rondo (223)',
  'P. Gasol (4.3)'],
 ['NBA',
  'Los Angeles Lakers',
  'Orlando Magic',
  'K. Bryant',
  '',
  'K. Bryant (695)',
  'D. Howard (353)',
  'R. Rondo (137)',
  'L. James (4.8)'],
 ['NBA',
  'Boston Celtics',
  'Los Angeles Lakers',
  'P. Pierce',
  '',
  'K. Bryant (633)',
  'K. Garnett (274)',
  'R. Rondo (172)',
  'K. Garnett (4.1)'],
 ['NBA',
  'San Antonio Spurs',
  'Cleveland Cavaliers',
  'T. Parker',
  '',
  'L. James (501)',
  'T. Duncan (229)',
  'L. James (159)',
  'L. James (3.7)'],
 ['NBA',
  'Miami Heat',
  'Dallas Mavericks',
  'D. Wade',
  '',
  'D. Wade (654)',
  'D. Nowitzki (268)',
  'S. Nash (204)',
  'D. Nowitzki (5.4)'],
 ['NBA',
  'San Antonio Spurs',
  'Detroit Pistons',
  'T. Duncan',
  '',
  'T. Duncan (542)',
  'T. Duncan (286)',
  'S. Nash (170)',
  'C. Billups (4.6)'],
 ['NBA',
  'Detroit Pistons',
  'Los Angeles Lakers',
  'C. Billups',
  '',
  'K. Bryant (539)',
  'B. Wallace (328)',
  'C. Billups (136)',
  "S. O'Neal (3.9)"],
 ['NBA',
  'San Antonio Spurs',
  'New Jersey Nets',
  'T. Duncan',
  '',
  'T. Duncan (593)',
  'T. Duncan (369)',
  'J. Kidd (163)',
  'T. Duncan (5.9)'],
 [''],
 ['NBA',
  'Los Angeles Lakers',
  'New Jersey Nets',
  "S. O'Neal",
  '',
  "S. O'Neal (541)",
  "S. O'Neal (239)",
  'J. Kidd (182)',
  "S. O'Neal (3.8)"],
 ['NBA',
  'Los Angeles Lakers',
  'Philadelphia 76ers',
  "S. O'Neal",
  '',
  'A. Iverson (723)',
  'D. Mutombo (316)',
  'A. Iverson (134)',
  'K. Bryant (3.8)'],
 ['NBA',
  'Los Angeles Lakers',
  'Indiana Pacers',
  "S. O'Neal",
  '',
  "S. O'Neal (707)",
  "S. O'Neal (355)",
  'M. Jackson (178)',
  "S. O'Neal (4.7)"],
 ['NBA',
  'San Antonio Spurs',
  'New York Knicks',
  'T. Duncan',
  '',
  'L. Sprewell (407)',
  'T. Duncan (195)',
  'A. Johnson (126)',
  'T. Duncan (3.7)'],
 ['NBA',
  'Chicago Bulls',
  'Utah Jazz',
  'M. Jordan',
  '',
  'M. Jordan (680)',
  'D. Rodman (248)',
  'J. Stockton (155)',
  'M. Jordan (4.8)'],
 ['NBA',
  'Chicago Bulls',
  'Utah Jazz',
  'M. Jordan',
  '',
  'M. Jordan (590)',
  'K. Malone (228)',
  'J. Stockton (191)',
  'M. Jordan (3.9)'],
 ['NBA',
  'Chicago Bulls',
  'Seattle SuperSonics',
  'M. Jordan',
  '',
  'M. Jordan (552)',
  'D. Rodman (247)',
  'J. Stockton (195)',
  'M. Jordan (4.7)'],
 ['NBA',
  'Houston Rockets',
  'Orlando Magic',
  'H. Olajuwon',
  '',
  'H. Olajuwon (725)',
  "S. O'Neal (250)",
  'A. Hardaway (162)',
  "S. O'Neal (3.0)"],
 ['NBA',
  'Houston Rockets',
  'New York Knicks',
  'H. Olajuwon',
  '',
  'H. Olajuwon (664)',
  'P. Ewing (293)',
  'J. Stockton (157)',
  'H. Olajuwon (4.3)'],
 ['NBA',
  'Chicago Bulls',
  'Phoenix Suns',
  'M. Jordan',
  '',
  'M. Jordan (666)',
  'C. Barkley (326)',
  'K. Johnson (182)',
  'C. Barkley (4.6)'],
 ['NBA',
  'Chicago Bulls',
  'Portland Trail Blazers',
  'M. Jordan',
  '',
  'M. Jordan (759)',
  'H. Grant (194)',
  'J. Stockton (217)',
  'M. Jordan (4.1)'],
 ['NBA',
  'Chicago Bulls',
  'Los Angeles Lakers',
  'M. Jordan',
  '',
  'M. Jordan (529)',
  'D. Rodman (177)',
  'M. Johnson (240)',
  'M. Jordan (4.8)'],
 ['NBA',
  'Detroit Pistons',
  'Portland Trail Blazers',
  'I. Thomas',
  '',
  'M. Jordan (587)',
  'B. Laimbeer (211)',
  'K. Johnson (170)',
  'M. Jordan (4.0)'],
 ['NBA',
  'Detroit Pistons',
  'Los Angeles Lakers',
  'J. Dumars',
  '',
  'M. Jordan (591)',
  'D. Rodman (170)',
  'M. Johnson (165)',
  'M. Jordan (4.0)'],
 ['NBA',
  'Los Angeles Lakers',
  'Detroit Pistons',
  'J. Worthy',
  '',
  'J. Worthy (506)',
  'B. Laimbeer (221)',
  'M. Johnson (303)',
  'M. Johnson (4.0)'],
 ['NBA',
  'Los Angeles Lakers',
  'Boston Celtics',
  'M. Johnson',
  '',
  'L. Bird (622)',
  'L. Bird (231)',
  'M. Johnson (219)',
  'M. Johnson (3.7)'],
 ['NBA',
  'Boston Celtics',
  'Houston Rockets',
  'L. Bird',
  '',
  'H. Olajuwon (537)',
  'H. Olajuwon (236)',
  'M. Johnson (211)',
  'L. Bird (4.2)'],
 ['NBA',
  'Los Angeles Lakers',
  'Boston Celtics',
  'K. Abdul-Jabbar',
  '',
  'L. Bird (520)',
  'R. Parish (219)',
  'M. Johnson (289)',
  'M. Johnson (3.0)'],
 ['NBA',
  'Boston Celtics',
  'Los Angeles Lakers',
  'L. Bird',
  '',
  'L. Bird (632)',
  'L. Bird (252)',
  'M. Johnson (284)',
  'L. Bird (4.7)'],
 ['NBA',
  'Philadelphia 76ers',
  'Los Angeles Lakers',
  'M. Malone',
  '',
  'K. Abdul-Jabbar (406)',
  'M. Malone (206)',
  'M. Johnson (192)',
  'M. Malone (2.8)']]

In [12]:
#adding years into rows_data
last_year = 2022
for i in range(0, len(rows_data)):
    rows_data[i].insert(0, last_year)
    last_year -= 1

In [13]:
rows_data

[[2022,
  'NBA',
  'Golden State Warriors',
  'Boston Celtics',
  'S. Curry',
  '',
  'J. Tatum (615)',
  'A. Horford (214)',
  'J. Tatum (148)',
  'J. Butler (3.8)'],
 [2021,
  'NBA',
  'Milwaukee Bucks',
  'Phoenix Suns',
  'G. Antetokounmpo',
  '',
  'G. Antetokounmpo (634)',
  'G. Antetokounmpo (269)',
  'J. Holiday (199)',
  'G. Antetokounmpo (3.7)'],
 [2020,
  'NBA',
  'Los Angeles Lakers',
  'Miami Heat',
  'L. James',
  '',
  'A. Davis (582)',
  'L. James (226)',
  'L. James (184)',
  'A. Davis (4.5)'],
 [2019,
  'NBA',
  'Toronto Raptors',
  'Golden State Warriors',
  'K. Leonard',
  '',
  'K. Leonard (732)',
  'D. Green (223)',
  'D. Green (187)',
  'K. Leonard (4.9)'],
 [2018,
  'NBA',
  'Golden State Warriors',
  'Cleveland Cavaliers',
  'K. Durant',
  '',
  'L. James (748)',
  'D. Green (222)',
  'L. James (198)',
  'L. James (5.2)'],
 [2017,
  'NBA',
  'Golden State Warriors',
  'Cleveland Cavaliers',
  'K. Durant',
  '',
  'L. James (591)',
  'K. Love (191)',
  'L. James (141)',
  'L. James (4.3)'],
 [2016,
  'NBA',
  'Cleveland Cavaliers',
  'Golden State Warriors',
  'L. James',
  '',
  'K. Thompson (582)',
  'D. Green (228)',
  'R. Westbrook (198)',
  'L. James (4.7)'],
 [2015,
  'NBA',
  'Golden State Warriors',
  'Cleveland Cavaliers',
  'A. Iguodala',
  '',
  'L. James (601)',
  'D. Howard (238)',
  'L. James (169)',
  'S. Curry (3.9)'],
 [2014,
  'NBA',
  'San Antonio Spurs',
  'Miami Heat',
  'K. Leonard',
  '',
  'K. Durant (563)',
  'T. Duncan (211)',
  'R. Westbrook (153)',
  'L. James (4.3)'],
 [2013,
  'NBA',
  'Miami Heat',
  'San Antonio Spurs',
  'L. James',
  '',
  'L. James (596)',
  'T. Duncan (214)',
  'L. James (152)',
  'L. James (5.2)'],
 [2012,
  'NBA',
  'Miami Heat',
  'Oklahoma City Thunder',
  'L. James',
  '',
  'L. James (697)',
  'L. James (224)',
  'R. Rondo (227)',
  'L. James (5.8)'],
 [2011,
  'NBA',
  'Dallas Mavericks',
  'Miami Heat',
  'D. Nowitzki',
  '',
  'D. Nowitzki (582)',
  'T. Chandler (193)',
  'J. Kidd (153)',
  'L. James (3.8)'],
 [2010,
  'NBA',
  'Los Angeles Lakers',
  'Boston Celtics',
  'K. Bryant',
  '',
  'K. Bryant (671)',
  'P. Gasol (255)',
  'R. Rondo (223)',
  'P. Gasol (4.3)'],
 [2009,
  'NBA',
  'Los Angeles Lakers',
  'Orlando Magic',
  'K. Bryant',
  '',
  'K. Bryant (695)',
  'D. Howard (353)',
  'R. Rondo (137)',
  'L. James (4.8)'],
 [2008,
  'NBA',
  'Boston Celtics',
  'Los Angeles Lakers',
  'P. Pierce',
  '',
  'K. Bryant (633)',
  'K. Garnett (274)',
  'R. Rondo (172)',
  'K. Garnett (4.1)'],
 [2007,
  'NBA',
  'San Antonio Spurs',
  'Cleveland Cavaliers',
  'T. Parker',
  '',
  'L. James (501)',
  'T. Duncan (229)',
  'L. James (159)',
  'L. James (3.7)'],
 [2006,
  'NBA',
  'Miami Heat',
  'Dallas Mavericks',
  'D. Wade',
  '',
  'D. Wade (654)',
  'D. Nowitzki (268)',
  'S. Nash (204)',
  'D. Nowitzki (5.4)'],
 [2005,
  'NBA',
  'San Antonio Spurs',
  'Detroit Pistons',
  'T. Duncan',
  '',
  'T. Duncan (542)',
  'T. Duncan (286)',
  'S. Nash (170)',
  'C. Billups (4.6)'],
 [2004,
  'NBA',
  'Detroit Pistons',
  'Los Angeles Lakers',
  'C. Billups',
  '',
  'K. Bryant (539)',
  'B. Wallace (328)',
  'C. Billups (136)',
  "S. O'Neal (3.9)"],
 [2003,
  'NBA',
  'San Antonio Spurs',
  'New Jersey Nets',
  'T. Duncan',
  '',
  'T. Duncan (593)',
  'T. Duncan (369)',
  'J. Kidd (163)',
  'T. Duncan (5.9)'],
 [2002, ''],
 [2001,
  'NBA',
  'Los Angeles Lakers',
  'New Jersey Nets',
  "S. O'Neal",
  '',
  "S. O'Neal (541)",
  "S. O'Neal (239)",
  'J. Kidd (182)',
  "S. O'Neal (3.8)"],
 [2000,
  'NBA',
  'Los Angeles Lakers',
  'Philadelphia 76ers',
  "S. O'Neal",
  '',
  'A. Iverson (723)',
  'D. Mutombo (316)',
  'A. Iverson (134)',
  'K. Bryant (3.8)'],
 [1999,
  'NBA',
  'Los Angeles Lakers',
  'Indiana Pacers',
  "S. O'Neal",
  '',
  "S. O'Neal (707)",
  "S. O'Neal (355)",
  'M. Jackson (178)',
  "S. O'Neal (4.7)"],
 [1998,
  'NBA',
  'San Antonio Spurs',
  'New York Knicks',
  'T. Duncan',
  '',
  'L. Sprewell (407)',
  'T. Duncan (195)',
  'A. Johnson (126)',
  'T. Duncan (3.7)'],
 [1997,
  'NBA',
  'Chicago Bulls',
  'Utah Jazz',
  'M. Jordan',
  '',
  'M. Jordan (680)',
  'D. Rodman (248)',
  'J. Stockton (155)',
  'M. Jordan (4.8)'],
 [1996,
  'NBA',
  'Chicago Bulls',
  'Utah Jazz',
  'M. Jordan',
  '',
  'M. Jordan (590)',
  'K. Malone (228)',
  'J. Stockton (191)',
  'M. Jordan (3.9)'],
 [1995,
  'NBA',
  'Chicago Bulls',
  'Seattle SuperSonics',
  'M. Jordan',
  '',
  'M. Jordan (552)',
  'D. Rodman (247)',
  'J. Stockton (195)',
  'M. Jordan (4.7)'],
 [1994,
  'NBA',
  'Houston Rockets',
  'Orlando Magic',
  'H. Olajuwon',
  '',
  'H. Olajuwon (725)',
  "S. O'Neal (250)",
  'A. Hardaway (162)',
  "S. O'Neal (3.0)"],
 [1993,
  'NBA',
  'Houston Rockets',
  'New York Knicks',
  'H. Olajuwon',
  '',
  'H. Olajuwon (664)',
  'P. Ewing (293)',
  'J. Stockton (157)',
  'H. Olajuwon (4.3)'],
 [1992,
  'NBA',
  'Chicago Bulls',
  'Phoenix Suns',
  'M. Jordan',
  '',
  'M. Jordan (666)',
  'C. Barkley (326)',
  'K. Johnson (182)',
  'C. Barkley (4.6)'],
 [1991,
  'NBA',
  'Chicago Bulls',
  'Portland Trail Blazers',
  'M. Jordan',
  '',
  'M. Jordan (759)',
  'H. Grant (194)',
  'J. Stockton (217)',
  'M. Jordan (4.1)'],
 [1990,
  'NBA',
  'Chicago Bulls',
  'Los Angeles Lakers',
  'M. Jordan',
  '',
  'M. Jordan (529)',
  'D. Rodman (177)',
  'M. Johnson (240)',
  'M. Jordan (4.8)'],
 [1989,
  'NBA',
  'Detroit Pistons',
  'Portland Trail Blazers',
  'I. Thomas',
  '',
  'M. Jordan (587)',
  'B. Laimbeer (211)',
  'K. Johnson (170)',
  'M. Jordan (4.0)'],
 [1988,
  'NBA',
  'Detroit Pistons',
  'Los Angeles Lakers',
  'J. Dumars',
  '',
  'M. Jordan (591)',
  'D. Rodman (170)',
  'M. Johnson (165)',
  'M. Jordan (4.0)'],
 [1987,
  'NBA',
  'Los Angeles Lakers',
  'Detroit Pistons',
  'J. Worthy',
  '',
  'J. Worthy (506)',
  'B. Laimbeer (221)',
  'M. Johnson (303)',
  'M. Johnson (4.0)'],
 [1986,
  'NBA',
  'Los Angeles Lakers',
  'Boston Celtics',
  'M. Johnson',
  '',
  'L. Bird (622)',
  'L. Bird (231)',
  'M. Johnson (219)',
  'M. Johnson (3.7)'],
 [1985,
  'NBA',
  'Boston Celtics',
  'Houston Rockets',
  'L. Bird',
  '',
  'H. Olajuwon (537)',
  'H. Olajuwon (236)',
  'M. Johnson (211)',
  'L. Bird (4.2)'],
 [1984,
  'NBA',
  'Los Angeles Lakers',
  'Boston Celtics',
  'K. Abdul-Jabbar',
  '',
  'L. Bird (520)',
  'R. Parish (219)',
  'M. Johnson (289)',
  'M. Johnson (3.0)'],
 [1983,
  'NBA',
  'Boston Celtics',
  'Los Angeles Lakers',
  'L. Bird',
  '',
  'L. Bird (632)',
  'L. Bird (252)',
  'M. Johnson (284)',
  'L. Bird (4.7)'],
 [1982,
  'NBA',
  'Philadelphia 76ers',
  'Los Angeles Lakers',
  'M. Malone',
  '',
  'K. Abdul-Jabbar (406)',
  'M. Malone (206)',
  'M. Johnson (192)',
  'M. Malone (2.8)']]

In [14]:
#creating the dataframe
nba_finals = pd.DataFrame(rows_data, columns=headers)
nba_finals.head()

,Year,Lg,Champion,Runner-Up,Finals MVP,,Points,Rebounds,Assists,Win Shares
0,2022,NBA,Golden State Warriors,Boston Celtics,S. Curry,,J. Tatum (615),A. Horford (214),J. Tatum (148),J. Butler (3.8)
1,2021,NBA,Milwaukee Bucks,Phoenix Suns,G. Antetokounmpo,,G. Antetokounmpo (634),G. Antetokounmpo (269),J. Holiday (199),G. Antetokounmpo (3.7)
2,2020,NBA,Los Angeles Lakers,Miami Heat,L. James,,A. Davis (582),L. James (226),L. James (184),A. Davis (4.5)
3,2019,NBA,Toronto Raptors,Golden State Warriors,K. Leonard,,K. Leonard (732),D. Green (223),D. Green (187),K. Leonard (4.9)
4,2018,NBA,Golden State Warriors,Cleveland Cavaliers,K. Durant,,L. James (748),D. Green (222),L. James (198),L. James (5.2)

In [15]:
nba_finals.columns

Index(['Year', 'Lg', 'Champion', 'Runner-Up', 'Finals MVP', ' ', 'Points',
       'Rebounds', 'Assists', 'Win Shares'],
      dtype='object')

In [16]:
#dropping the whitespace column
nba_finals.drop('\xa0',axis=1,inplace=True)

In [17]:
nba_finals.columns

Index(['Year', 'Lg', 'Champion', 'Runner-Up', 'Finals MVP', 'Points',
       'Rebounds', 'Assists', 'Win Shares'],
      dtype='object')

In [18]:
nba_finals.head()

,Year,Lg,Champion,Runner-Up,Finals MVP,Points,Rebounds,Assists,Win Shares
0,2022,NBA,Golden State Warriors,Boston Celtics,S. Curry,J. Tatum (615),A. Horford (214),J. Tatum (148),J. Butler (3.8)
1,2021,NBA,Milwaukee Bucks,Phoenix Suns,G. Antetokounmpo,G. Antetokounmpo (634),G. Antetokounmpo (269),J. Holiday (199),G. Antetokounmpo (3.7)
2,2020,NBA,Los Angeles Lakers,Miami Heat,L. James,A. Davis (582),L. James (226),L. James (184),A. Davis (4.5)
3,2019,NBA,Toronto Raptors,Golden State Warriors,K. Leonard,K. Leonard (732),D. Green (223),D. Green (187),K. Leonard (4.9)
4,2018,NBA,Golden State Warriors,Cleveland Cavaliers,K. Durant,L. James (748),D. Green (222),L. James (198),L. James (5.2)

In [19]:
nba_finals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        41 non-null     int64
 1   Lg          41 non-null     object
 2   Champion    40 non-null     object
 3   Runner-Up   40 non-null     object
 4   Finals MVP  40 non-null     object
 5   Points      40 non-null     object
 6   Rebounds    40 non-null     object
 7   Assists     40 non-null     object
 8   Win Shares  40 non-null     object
dtypes: int64(1), object(8)
memory usage: 3.0+ KB

In [20]:
#searching for missing values
nba_finals.isnull()

,Year,Lg,Champion,Runner-Up,Finals MVP,Points,Rebounds,Assists,Win Shares
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,False,False,True,True,True,True,True,True,True
21,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False

#### Only the 20th row is missing data

In [21]:
nba_finals.iloc[20]

Year          2002
Lg
Champion      None
Runner-Up     None
Finals MVP    None
Points        None
Rebounds      None
Assists       None
Win Shares    None
Name: 20, dtype: object

In [22]:
#filling in the missing values
nba_finals.fillna({"Champion":"Los Angeles Lakers","Runner-Up":"New Jersey Nets","Finals MVP":"S. O'Neal","Points":"S. O'Neal (541)", "Rebounds":"S. O'Neal (239)","Assists":"J. Kidd (182)","Win Shares":"S. O'Neal (3.8)"},inplace=True)

In [23]:
nba_finals["Lg"]

0     NBA
1     NBA
2     NBA
3     NBA
4     NBA
5     NBA
6     NBA
7     NBA
8     NBA
9     NBA
10    NBA
11    NBA
12    NBA
13    NBA
14    NBA
15    NBA
16    NBA
17    NBA
18    NBA
19    NBA
20
21    NBA
22    NBA
23    NBA
24    NBA
25    NBA
26    NBA
27    NBA
28    NBA
29    NBA
30    NBA
31    NBA
32    NBA
33    NBA
34    NBA
35    NBA
36    NBA
37    NBA
38    NBA
39    NBA
40    NBA
Name: Lg, dtype: object

In [24]:
nba_finals.at[20, "Lg"] = 'NBA'

In [25]:
nba_finals["Lg"]

0     NBA
1     NBA
2     NBA
3     NBA
4     NBA
5     NBA
6     NBA
7     NBA
8     NBA
9     NBA
10    NBA
11    NBA
12    NBA
13    NBA
14    NBA
15    NBA
16    NBA
17    NBA
18    NBA
19    NBA
20    NBA
21    NBA
22    NBA
23    NBA
24    NBA
25    NBA
26    NBA
27    NBA
28    NBA
29    NBA
30    NBA
31    NBA
32    NBA
33    NBA
34    NBA
35    NBA
36    NBA
37    NBA
38    NBA
39    NBA
40    NBA
Name: Lg, dtype: object

In [26]:
nba_finals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        41 non-null     int64
 1   Lg          41 non-null     object
 2   Champion    41 non-null     object
 3   Runner-Up   41 non-null     object
 4   Finals MVP  41 non-null     object
 5   Points      41 non-null     object
 6   Rebounds    41 non-null     object
 7   Assists     41 non-null     object
 8   Win Shares  41 non-null     object
dtypes: int64(1), object(8)
memory usage: 3.0+ KB

In [27]:
nba_finals.describe()

              Year
count    41.000000
mean   2002.000000
std      11.979149
min    1982.000000
25%    1992.000000
50%    2002.000000
75%    2012.000000
max    2022.000000

In [28]:
nba_finals.rename(columns = {"Lg":"League"},inplace=True)

### Data Discovery

#### Champions refers to the team that won that year's NBA playoffs (every league is NBA).

#### Runner-up is the team that lost the finals of that year's playoffs thus taking second place in the tournament (a.k.a Runner-up)

#### Finals MVP is the most valuable player in that year's playoffs final game.

#### Points refers to the player that scored the most points in that year playoffs, with the number of points scored in brackets. The NBA playoffs is the postseason tournament of the National Basketball Association (NBA) held to determine the league's champion. An annual best-of-seven elimination tournment, the NBA playoffs are held after the league's regular season and its preliminary postseason tournament, the NBA Play-in Tournament.

#### The playoffs are comprised of 16 teams in total- the eight best from each of the NBA's two conferences (East and West). The teams in each conference are ranked by their win-loss record from the regular season. The six teams with the most wins from each conference progress immediately to the playoffs. The NBA Play-In tournament determines the final two spots (the seventh and eighth seeds) of the main playoff brackets, using a four-team, three-game format. Within each conference, teams that finished ranked seventh-tenth play each other as follows.

#### Rebounds refers to the player with the highest number of rebounds in that playoff. A rebound is when a player gets the ball after it misses the hoop, hits off the backboard, or bounces off the rim. It occurs when a player gains possession of the basketball after a missed field goal, three-point field goal, or free throw attempt.

#### Win shares refers to the player that contributed the most to their team wins in that year's playoff.

### Data Manipulation

In [29]:
nba_finals.head()

,Year,League,Champion,Runner-Up,Finals MVP,Points,Rebounds,Assists,Win Shares
0,2022,NBA,Golden State Warriors,Boston Celtics,S. Curry,J. Tatum (615),A. Horford (214),J. Tatum (148),J. Butler (3.8)
1,2021,NBA,Milwaukee Bucks,Phoenix Suns,G. Antetokounmpo,G. Antetokounmpo (634),G. Antetokounmpo (269),J. Holiday (199),G. Antetokounmpo (3.7)
2,2020,NBA,Los Angeles Lakers,Miami Heat,L. James,A. Davis (582),L. James (226),L. James (184),A. Davis (4.5)
3,2019,NBA,Toronto Raptors,Golden State Warriors,K. Leonard,K. Leonard (732),D. Green (223),D. Green (187),K. Leonard (4.9)
4,2018,NBA,Golden State Warriors,Cleveland Cavaliers,K. Durant,L. James (748),D. Green (222),L. James (198),L. James (5.2)

#### Splitting the Points, Rebounds, Assists, Win Shares columns to create four additional columns.

In [30]:
nba_finals["Highest Total Points"] = pd.to_numeric(nba_finals["Points"].str.split('(').str[1].str.strip(')'))

In [31]:
nba_finals["Scored by"] = nba_finals["Points"].str.split('(').str[0].str.strip()

In [32]:
nba_finals["Highest Rebounds"] = pd.to_numeric(nba_finals["Rebounds"].str.split('(').str[1].str.strip(')'))

In [33]:
nba_finals["Caught by"] = nba_finals["Rebounds"].str.split('(').str[0].str.strip()

In [34]:
nba_finals["Highest Assists"] = pd.to_numeric(nba_finals["Assists"].str.split('(').str[1].str.strip(')'))

In [35]:
nba_finals["Made by"] = nba_finals["Assists"].str.split('(').str[0].str.strip()

In [36]:
nba_finals["Highest Win Shares"] = pd.to_numeric(nba_finals["Win Shares"].str.split('(').str[1].str.strip(')'))

In [37]:
nba_finals["Player with HWS"] = nba_finals["Win Shares"].str.split('(').str[0].str.strip()

In [38]:
nba_finals.drop(["Points","Rebounds","Assists","Win Shares"], axis=1,inplace=True)

In [39]:
nba_finals

,Year,League,Champion,Runner-Up,Finals MVP,Highest Total Points,Scored by,Highest Rebounds,Caught by,Highest Assists,Made by,Highest Win Shares,Player with HWS
0,2022,NBA,Golden State Warriors,Boston Celtics,S. Curry,615,J. Tatum,214,A. Horford,148,J. Tatum,3.8,J. Butler
1,2021,NBA,Milwaukee Bucks,Phoenix Suns,G. Antetokounmpo,634,G. Antetokounmpo,269,G. Antetokounmpo,199,J. Holiday,3.7,G. Antetokounmpo
2,2020,NBA,Los Angeles Lakers,Miami Heat,L. James,582,A. Davis,226,L. James,184,L. James,4.5,A. Davis
3,2019,NBA,Toronto Raptors,Golden State Warriors,K. Leonard,732,K. Leonard,223,D. Green,187,D. Green,4.9,K. Leonard
4,2018,NBA,Golden State Warriors,Cleveland Cavaliers,K. Durant,748,L. James,222,D. Green,198,L. James,5.2,L. James
5,2017,NBA,Golden State Warriors,Cleveland Cavaliers,K. Durant,591,L. James,191,K. Love,141,L. James,4.3,L. James
6,2016,NBA,Cleveland Cavaliers,Golden State Warriors,L. James,582,K. Thompson,228,D. Green,198,R. Westbrook,4.7,L. James
7,2015,NBA,Golden State Warriors,Cleveland Cavaliers,A. Iguodala,601,L. James,238,D. Howard,169,L. James,3.9,S. Curry
8,2014,NBA,San Antonio Spurs,Miami Heat,K. Leonard,563,K. Durant,211,T. Duncan,153,R. Westbrook,4.3,L. James
9,2013,NBA,Miami Heat,San Antonio Spurs,L. James,596,L. James,214,T. Duncan,152,L. James,5.2,L. James
10,2012,NBA,Miami Heat,Oklahoma City Thunder,L. James,697,L. James,224,L. James,227,R. Rondo,5.8,L. James
11,2011,NBA,Dallas Mavericks,Miami Heat,D. Nowitzki,582,D. Nowitzki,193,T. Chandler,153,J. Kidd,3.8,L. James
12,2010,NBA,Los Angeles Lakers,Boston Celtics,K. Bryant,671,K. Bryant,255,P. Gasol,223,R. Rondo,4.3,P. Gasol
13,2009,NBA,Los Angeles Lakers,Orlando Magic,K. Bryant,695,K. Bryant,353,D. Howard,137,R. Rondo,4.8,L. James
14,2008,NBA,Boston Celtics,Los Angeles Lakers,P. Pierce,633,K. Bryant,274,K. Garnett,172,R. Rondo,4.1,K. Garnett
15,2007,NBA,San Antonio Spurs,Cleveland Cavaliers,T. Parker,501,L. James,229,T. Duncan,159,L. James,3.7,L. James
16,2006,NBA,Miami Heat,Dallas Mavericks,D. Wade,654,D. Wade,268,D. Nowitzki,204,S. Nash,5.4,D. Nowitzki
17,2005,NBA,San Antonio Spurs,Detroit Pistons,T. Duncan,542,T. Duncan,286,T. Duncan,170,S. Nash,4.6,C. Billups
18,2004,NBA,Detroit Pistons,Los Angeles Lakers,C. Billups,539,K. Bryant,328,B. Wallace,136,C. Billups,3.9,S. O'Neal
19,2003,NBA,San Antonio Spurs,New Jersey Nets,T. Duncan,593,T. Duncan,369,T. Duncan,163,J. Kidd,5.9,T. Duncan
20,2002,NBA,Los Angeles Lakers,New Jersey Nets,S. O'Neal,541,S. O'Neal,239,S. O'Neal,182,J. Kidd,3.8,S. O'Neal
21,2001,NBA,Los Angeles Lakers,New Jersey Nets,S. O'Neal,541,S. O'Neal,239,S. O'Neal,182,J. Kidd,3.8,S. O'Neal
22,2000,NBA,Los Angeles Lakers,Philadelphia 76ers,S. O'Neal,723,A. Iverson,316,D. Mutombo,134,A. Iverson,3.8,K. Bryant
23,1999,NBA,Los Angeles Lakers,Indiana Pacers,S. O'Neal,707,S. O'Neal,355,S. O'Neal,178,M. Jackson,4.7,S. O'Neal
24,1998,NBA,San Antonio Spurs,New York Knicks,T. Duncan,407,L. Sprewell,195,T. Duncan,126,A. Johnson,3.7,T. Duncan
25,1997,NBA,Chicago Bulls,Utah Jazz,M. Jordan,680,M. Jordan,248,D. Rodman,155,J. Stockton,4.8,M. Jordan
26,1996,NBA,Chicago Bulls,Utah Jazz,M. Jordan,590,M. Jordan,228,K. Malone,191,J. Stockton,3.9,M. Jordan
27,1995,NBA,Chicago Bulls,Seattle SuperSonics,M. Jordan,552,M. Jordan,247,D. Rodman,195,J. Stockton,4.7,M. Jordan
28,1994,NBA,Houston Rockets,Orlando Magic,H. Olajuwon,725,H. Olajuwon,250,S. O'Neal,162,A. Hardaway,3.0,S. O'Neal
29,1993,NBA,Houston Rockets,New York Knicks,H. Olajuwon,664,H. Olajuwon,293,P. Ewing,157,J. Stockton,4.3,H. Olajuwon
30,1992,NBA,Chicago Bulls,Phoenix Suns,M. Jordan,666,M. Jordan,326,C. Barkley,182,K. Johnson,4.6,C. Barkley
31,1991,NBA,Chicago Bulls,Portland Trail Blazers,M. Jordan,759,M. Jordan,194,H. Grant,217,J. Stockton,4.1,M. Jordan
32,1990,NBA,Chicago Bulls,Los Angeles Lakers,M. Jordan,529,M. Jordan,177,D. Rodman,240,M. Johnson,4.8,M. Jordan
33,1989,NBA,Detroit Pistons,Portland Trail Blazers,I. Thomas,587,M. Jordan,211,B. Laimbeer,170,K. Johnson,4.0,M. Jordan
34,1988,NBA,Detroit Pistons,Los Angeles Lakers,J. Dumars,591,M. Jordan,170,D. Rodman,165,M. Johnson,4.0,M. Jordan
35,1987,NBA,Los Angeles Lakers,Detroit Pistons,J. Worthy,506,J. Worthy,221,B. Laimbeer,303,M. Johnson,4.0,M. Johnson
36,1986,NBA,Los Angeles Lakers,Boston Celtics,M. Johnson,622,L. Bird,231,L. Bird,219,M. Johnson,3.7,M. Johnson
37,1985,NBA,Boston Celtics,Houston Rockets,L. Bird,537,H. Olajuwon,236,H. Olajuwon,211,M. Johnson,4.2,L. Bird
38,1984,NBA,Los Angeles Lakers,Boston Celtics,K. Abdul-Jabbar,520,L. Bird,219,R. Parish,289,M. Johnson,3.0,M. Johnson
39,1983,NBA,Boston Celtics,Los Angeles Lakers,L. Bird,632,L. Bird,252,L. Bird,284,M. Johnson,4.7,L. Bird
40,1982,NBA,Philadelphia 76ers,Los Angeles Lakers,M. Malone,406,K. Abdul-Jabbar,206,M. Malone,192,M. Johnson,2.8,M. Malone

In [40]:
nba_finals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  41 non-null     int64
 1   League                41 non-null     object
 2   Champion              41 non-null     object
 3   Runner-Up             41 non-null     object
 4   Finals MVP            41 non-null     object
 5   Highest Total Points  41 non-null     int64
 6   Scored by             41 non-null     object
 7   Highest Rebounds      41 non-null     int64
 8   Caught by             41 non-null     object
 9   Highest Assists       41 non-null     int64
 10  Made by               41 non-null     object
 11  Highest Win Shares    41 non-null     float64
 12  Player with HWS       41 non-null     object
dtypes: float64(1), int64(4), object(8)
memory usage: 4.3+ KB

### EXPLORATORY DATA ANALYSIS

In [41]:
nba_finals.corr()

,Year,Highest Total Points,Highest Rebounds,Highest Assists,Highest Win Shares
Year,1.000000,0.257277,0.037175,-0.418909,0.323496
Highest Total Points,0.257277,1.000000,0.321165,-0.048310,0.390516
Highest Rebounds,0.037175,0.321165,1.000000,-0.225206,0.284492
Highest Assists,-0.418909,-0.048310,-0.225206,1.000000,0.020659
Highest Win Shares,0.323496,0.390516,0.284492,0.020659,1.000000

#### I will be using tableau to visualize the data.

In [42]:
nba_finals.to_csv("nba.csv")